# Info for pixi-build, to build caiman as an editable package for including in other environments
[package]
version = "1.13.2"  # see: https://github.com/prefix-dev/pixi/issues/2946

[package.build.backend]
name = "pixi-build-python"
version = "0.*"

[package.build.config]
ignore-pypi-mapping = false
extra-args = ["-Ceditable_mode=compat"]

[package.host-dependencies]
uv = "*"  # added for faster installation

# Environment specification for using just caiman
[workspace]
preview = ["pixi-build"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]

[feature.caiman.dependencies]
caiman = { path = "." }

# this is required to satisfy dependency of cuda builds on __cuda virtual package
[feature.cuda.system-requirements]
cuda = "12"

[feature.cuda.dependencies]
pytorch = { version = "*", build = "cuda*" }

# cuda pytorch doesn't exist for osx, so don't require it for default environment
[feature.cuda.target.osx-64.dependencies]
pytorch = { version = "*" }

[feature.cuda.target.osx-arm64.dependencies]
pytorch = { version = "*" }

[environments]
default = { features = ["caiman", "cuda"] }
cpu = { features = ["caiman"] }
